CREATE DATABASE IF NOT EXISTS music_library CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE music_library;

CREATE TABLE IF NOT EXISTS tracks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  no INT NOT NULL,
  title VARCHAR(191) NOT NULL,
  duration VARCHAR(10) NOT NULL,
  year INT NOT NULL,
  slug VARCHAR(191) NOT NULL UNIQUE,
  description TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
